.gitignore
develop/tutorials/articles/navigation/extending-form-navigators-with-new-sections-and-categories-intro.markdown

Please see ticket for comments.
https://issues.liferay.com/browse/LRDOCS-1739

Needs Organization

---

discover/portal/articles/07-collaborating/00-collaborating-intro.markdown
discover/portal/articles/07-collaborating/01-publishing-blogs.markdown

Please see ticket for comments.

Please check for accuracy and/or optimize.

---

discover/deployment/articles-dxp/02-liferay-connected-services/02-activating-dxp/00-intro.markdown

Added a note about activating local DXP instances to LCS activation intro.

LRDOCS-2653 LCS note

---

develop/tutorials/articles/340-data-upgrades-and-verifiers/creating-an-upgrade-process-for-your-application.markdown

Please see comments in file sent separately.

Please revise.

---

develop/tutorials/articles/192-item-selector/00-item-selector-intro.markdown
develop/tutorials/articles/192-item-selector/01-selecting-entities-using-the-item-selector.markdown
develop/tutorials/articles/260-themes-and-layout-templates/embedding-portlets-in-themes-and-layout-templates.markdown

Questions sent via email. Please also create the requested reference doc. These are quick revisions; if you can turn this around today, we can still publish.

Easy revisions

---

discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-3715 cc @chrislui

LRDOCS-3715, add headings and links for convenience

---

discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/05-publishing-assets.markdown

https://issues.liferay.com/browse/LRDOCS-1074 (note: the commit reference the wrong ticket.)

LRDOCS-1074 added information to 7.0 docs

---

discover/portal/articles/11-using-web-forms-and-dynamic-data-lists/03-creating-custom-displays.markdown

https://issues.liferay.com/browse/LRDOCS-835

LRDOCS-835 Updated new content for clarity and usefulness 

---

discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/05-publishing-assets.markdown

Minor code fix to workflow section

---

develop/tutorials/articles/100-tooling/05-maven/04-deploying-a-module-built-with-maven-to-liferay.markdown

These are the formatting issues we talked about yesterday.

Fix formatting problems

---

discover/portal/articles/03-advanced-web-content-management/01-advanced-content-with-structures-and-templates.markdown

https://issues.liferay.com/browse/LRDOCS-835

LRDOCS-835 Added sidebar to structures and templates article

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/04-upgrading-portlets-that-use-service-builder.markdown
discover/deployment/articles/06-upgrading-liferay/00-upgrading-liferay-intro.markdown

Please clarify exceptions section

As discussed; thanks!

---

develop/reference/articles/10-gradle/05-css-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/10-jasper-jspc-gradle-plugin.markdown
develop/reference/articles/10-gradle/12-js-module-config-generator-gradle-plugin.markdown
develop/reference/articles/10-gradle/13-js-transpiler-gradle-plugin.markdown
develop/reference/articles/10-gradle/14-lang-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/17-service-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/18-source-formatter-gradle-plugin.markdown

This is typically a weekly PR I submit to update our Gradle plugin reference docs. These changes bring our LDN docs up-to-date with our current Gradle plugins.

Gradle Reference Doc Updates

---

develop/tutorials/articles/300-osgi-basics/04-overriding-service-references.markdown
develop/tutorials/articles/310-troubleshooting/03-resolving-cnfe-and-cdnfe-in-osgi-bundles.markdown

LRDOCS-3938 Config cfg syntax

---

discover/deployment/articles/03-configuring-liferay/02-document-repository.markdown
discover/portal/articles/03-collaboration/01-managing-documents-and-media/03-liferay-repository-types.markdown

@jhinkey see https://issues.liferay.com/browse/LPS-72058 . The ticket isn't closed, but the FP and GA have already been released, so this deprecation should be included in those.

LRDOCS-3935 added JCR Store deprecation note

---

develop/tutorials/articles/110-portlets/03-spring-mvc/00-spring-mvc-intro.markdown
develop/tutorials/articles/310-troubleshooting/03-resolving-cnfe-and-cdnfe-in-osgi-bundles.markdown

This looks good, but there are duplicate file numbers in the 310-troubleshooting folder. I'm really backed up on my PRs; can you fix? Thanks!

Wordsmithed; file order needs updating

---

develop/tutorials/articles/160-import-export-and-staging/06-developing-data-handlers.markdown

https://issues.liferay.com/browse/LRDOCS-4124

LRDOCS-4124 Data Handler Notes

---

develop/tutorials/articles/300-osgi-basics/03-adding-third-party-libraries-to-a-module.markdown

Please determine if there's a recommended approach (i.e., only expand as a last resort, or whatever).

Looks good, but is bare on recommendations.

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process.markdown

I also have one in-line comment on a sentence fragment I can't figure out the meaning of.

LRDOCS-5296 Too long. Please split up.

---

develop/tutorials/articles/400-back-end-frameworks/00-back-end-frameworks-intro.markdown
develop/tutorials/articles/400-back-end-frameworks/02-portlet-providers/00-portlet-providers-intro.markdown

Please see comments in ticket.

LRDOCS-4704 Portlet Providers

---

distribute/publish/articles/01-publishing-your-app/05-managing-your-published-app/00-managing-your-app-intro.markdown

This is over 1700 words. Please break it up.

LRDOCS-4714 Managing Your App

---

developer/frameworks/articles/02-dependency-injection/01-dependency-injection-intro.markdown
developer/frameworks/articles/02-dependency-injection/05-osgi-cdi-integration/01-osgi-cdi-integration-intro.markdown
developer/frameworks/articles/02-dependency-injection/05-osgi-cdi-integration/02-publishing-cdi-beans-as-osgi-services.markdown
developer/frameworks/articles/02-dependency-injection/05-osgi-cdi-integration/03-using-osgi-services-in-a-bean.markdown

Please see comments in file and sent separately. Thanks!

LRDOCS-6088 Wordsmithed; needs intro work

---

deployment/articles/05-upgrading-to-liferay-7-2/03-test-upgrading-a-liferay-backup-copy.markdown

This needs some sample API code to help administrators make the API calls to find orphaned objects. Please provide these as discussed. @achaparro

LRDOCS-6527 Wordsmithed. Please provide example code.

---

deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/02-tuning-for-the-data-upgrade.markdown

See comments in ticket; thanks!

LRDOCS-6432 Wordsmithed; missing supported databases

---

develop/tutorials/articles/140-application-security/01-application-permissions/02-defining-permissions.markdown

https://issues.liferay.com/browse/LRDOCS-6627 7.1.x Clarify when default permissions are added to the database

LRDOCS-6627 7.1.x Clarify when default permissions are added to the database
